export const lasforstaelse2 = [
    { order: 0, question: "Vad är viktigast när man spelar fotboll?", type: "answerAlt", alt1: "A) Bra fotbollsskor", alt2: "B) En fotboll", alt3: "C) God teknik", alt4: "D) Bra lagkamrater", correct: "B) En fotboll", questionWith:"100%" },
    { order: 1, question: "Vad lär du dig när du tränar fotboll? (Skriv två saker som står i texten)", type: "textarea", alt1: "", alt2: "", alt3: "", alt4: "", correct: "", questionWith:"500px"},
    { order: 2, question: "Vilken var den första beskrivningen av sporten? (Välj den beskrivning som kom first i texten)", type: "answerAlt", alt1: "Man kan spela var som helst.", alt2: "Det är världens största lagsport.", alt3: "Man måste känna till de regler som gäller.", alt4: "Man behöver träna för att få bra teknik.", correct: "Det är världens största lagsport.", questionWith:"700px" },
    { order: 3, question: "Vilken sorts berättelse vill Diego helst skriva?", type: "answerAlt", alt1: "A) Sorliga historier", alt2: "B) Spännande historier", alt3: "C) Historier om barn i världen", alt4: "D) Historier om Ryssland", correct: "B) Spännande historier", questionWith:"500px"},
    { order: 4, question: "Hur tycker Diego det är att skriva sorliga historier?", type: "answerAlt", alt1: "A) De går fortast att skriva", alt2: "B) De kan göra läsaren ledsen", alt3: "C) De är lättast att hitta på", alt4: "D) Hans pappa tycker om att läsa dem", correct: "C) De är lättast att hitta på", questionWith:"500px"},
    { order: 5, question: "Hur gör Diego när han skriver?", type: "answerAlt", alt1: "A) Han skriver genast färdigt berättelsen", alt2: "B) Han planerar först och skriver sedan en kort berättelse", alt3: "C) Han skriver utan att planera i förväg", alt4: "D) Han skriver två sidor och låter pappa läsa dem", correct: "D) Han skriver två sidor och låter pappa läsa dem", questionWith:"500px"},
    { order: 6, question: "Vad menas med att ´ha till hands´?", type: "answerAlt", alt1: "A) Att ha till hjälp", alt2: "B) Att ta hand om", alt3: "C) Att använda händerna", alt4: "D) Att skriva med penna", correct: "A) Att ha till hjälp", questionWith:"500px"},
    { order: 7, question: "Varför har Diego en lista med namn från olika länder?", type: "answerAlt", alt1: "A) Han vill skriva om barn i Chile", alt2: "B) Han hat många kompisar från olika länder", alt3: "C) Han vill bli journalist och resa till olika länder", alt4: "D) Den är bra att ha när man skriver", correct: "A) Han vill skriva om barn i Chile", questionWith:"500px"},
    { order: 8, question: "Texten om Diego handlar om ...", type: "answerAlt", alt1: "A) en pojke som vill bli journalist", alt2: "B) en pojke som vill arbeta på kontor", alt3: "C) en pojke som tycker om att skriva", alt4: "D) en pojke som vill resa ut i världen", correct: "C) en pojke som tycker om att skriva", questionWith:"500px"},
    { order: 9, question: "Vilka två skrivtips vill Diego ge dig?", type: "textarea", alt1: "", alt2: "", alt3: "", alt4: "", correct: "", questionWith:"500px"},

]